grafana:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

    hosts:
      - grafana.mithleshmeghwal.com

    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.mithleshmeghwal.com